$(document).ready(function(){$("#showcase").Cloud9Carousel({yPos:42,yRadius:48,mirrorOptions:{gap:12,height:.2},buttonLeft:$(".nav > .left"),buttonRight:$(".nav > .right"),autoPlay:!1,bringToFront:!0,onRendered:function(e){$("#item-title").attr("href",e.nearestItem().element.alt)},onLoaded:function(){$("#showcase").css("visibility","visible")
$("#showcase").css("display","none")
$("#showcase").fadeIn(1500)}})
$(".testimonials__item").click(function(){$(".testimonials__item").removeClass("active")
$(this).addClass("active")})
$(".prices__diagram-item").hover(function(){$(this).siblings().removeClass("active")
$(this).addClass("active")},function(){$("prices__map-item").removeClass("active")})
$(".tablet__menu-item").click(function(){$("#jsMenu").toggleClass("active")})
$("#jsMenuBtn").click(function(){$("#jsMenu").toggleClass("active")})
$("input, textarea").placeholder()
$.mask.definitions["~"]="[+-]"
    $.mask.definitions['9'] = ''
    $.mask.definitions['d'] = '[0-9]'
$(".phone").mask("+994(dd) ddd-dd-dd")
$(".prettyPhoto").prettyPhoto({hideflash:!0})
$(".lazy").lazyload({threshold:500})
$(".jsModalTrigger").popup()
$(".debF").click(function(e){
    e.preventDefault();
    var city = $(this).attr('href');
    $("#contacts__select").val(city);
    changeContacts($("#contacts__select"));
    $('html, body').animate({
        scrollTop: $("#YMapsID").offset().top
    }, 800);
})
$(".universities__btn").magnificPopup({type:"inline",fixedContentPos:!1,fixedBgPos:!0,overflowY:"auto",closeBtnInside:!0,preloader:!1,midClick:!0,removalDelay:300,mainClass:"my-mfp-zoom-in"})
$(".popup-youtube").magnificPopup({disableOn:700,type:"iframe",mainClass:"mfp-fade",removalDelay:160,preloader:!1,fixedContentPos:!1})
$(window).scroll(function(){$(this).scrollTop()>200?$("#jsScrollTop").fadeIn():$("#jsScrollTop").fadeOut()})
$(window).load(function(){$(".tablet__menu-item,.header__nav-item, #jsScrollTop").mPageScroll2id({scrollSpeed:500,offset:50,scrollEasing:"linear",scrollingEasing:"linear",highlightClass:"active"})})
$(this).scrollTop()>0&&$(".header").addClass("header--sticky"),$(window).scroll(function(){$(this).scrollTop()>0?$(".header").addClass("header--sticky"):$(".header").removeClass("header--sticky")})
$(".jsSlider-1").slick({arrows:!0,prevArrow:'<button type="button" data-role="none" class="slick-prev" aria-label="previous"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARpJREFUeNpi/P//PwMpgJGRsY2RFE1ADe1AiosBpIkQBqkH4lwgXgrmE6nJG4g3ATEbUZqAwBGIDwKxCFyMgAZNID4CxMIo4ng0CADxUSA2wpDDoUEEiPcCsQtWeRya1gJxCE5XYNEwH4gr8PkVHrnAiGMGUi1AzAIUK8UXySxI7AwgFgXidIJJA2pTDBBvgUUeEXHHYACNbRZiNMA0HQBia2I1wDQ5AfEykjRBdWYB8RqSNEE1VgPxRCBmJqSJCSkgO6F0BVFBjubJ1UCcQ5Tz0DRuBWIvUjVJQjOeOdGakDQeB2I9ojVBNepCcy4v0ZqQCpX9QMxDtCaoxnBoqHKSoglU7uUD8TyUTEhkCdsLilpGMsryPoAAAwBD49VaS2wWqwAAAABJRU5ErkJggg==" /></button>',nextArrow:'<button type="button" data-role="none" class="slick-next" aria-label="next"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARhJREFUeNpiYGBgmAnESv///2cgFoOAJxDvAmImojVBdSYD8QYgZiRaE1RjCRBPA2IWQpqYGBCgH4i/AnENAyGAxZNLgLiIKOehadwMxH6kahIH4v1AbE20JqhGMSA+BsT6RGuCatQB4iNAzEe0JqhGT6hT+YnWBNUYAsRrgZiDFE2MQFwIxPNBfEZYAiQGMDIyghLAA5I0QTWeItWmeiD1ixQ/pQHxKlICwhWItwExJ7HxZA2NYHFiU4QqEB8FJSli0x4fEB8GYjNiU7kwEO8FYndSssYaIA4jJrvD4mIekDoLlFyFM75gkQtUzAykGqHBWowvklmQ2GnQHJtOVMECBLHQcoGd2BLWBRpSTKQUy3NJLcsBAgwAKdbSmEpSh+IAAAAASUVORK5CYII=" /></button>',autoplay:!1,autoplaySpeed:3e3,lazyLoad:"ondemand",centerPadding:"50px",cssEase:"ease",dots:!1,dotsClass:"slick-dots",easing:"linear",fade:!0,focusOnSelect:!1,infinite:!0,pauseOnHover:!0,slide:"",slidesToShow:1,slidesToScroll:1,speed:500,variableWidth:!1})
$(".jsSlider-2").slick({arrows:!0,prevArrow:'<button type="button" data-role="none" class="slick-prev" aria-label="previous"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARpJREFUeNpi/P//PwMpgJGRsY2RFE1ADe1AiosBpIkQBqkH4lwgXgrmE6nJG4g3ATEbUZqAwBGIDwKxCFyMgAZNID4CxMIo4ng0CADxUSA2wpDDoUEEiPcCsQtWeRya1gJxCE5XYNEwH4gr8PkVHrnAiGMGUi1AzAIUK8UXySxI7AwgFgXidIJJA2pTDBBvgUUeEXHHYACNbRZiNMA0HQBia2I1wDQ5AfEykjRBdWYB8RqSNEE1VgPxRCBmJqSJCSkgO6F0BVFBjubJ1UCcQ5Tz0DRuBWIvUjVJQjOeOdGakDQeB2I9ojVBNepCcy4v0ZqQCpX9QMxDtCaoxnBoqHKSoglU7uUD8TyUTEhkCdsLilpGMsryPoAAAwBD49VaS2wWqwAAAABJRU5ErkJggg==" /><button type="button" data-role="none" class="slick-prev" aria-label="previous"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARpJREFUeNpi/P//PwMpgJGRsY2RFE1ADe1AiosBpIkQBqkH4lwgXgrmE6nJG4g3ATEbUZqAwBGIDwKxCFyMgAZNID4CxMIo4ng0CADxUSA2wpDDoUEEiPcCsQtWeRya1gJxCE5XYNEwH4gr8PkVHrnAiGMGUi1AzAIUK8UXySxI7AwgFgXidIJJA2pTDBBvgUUeEXHHYACNbRZiNMA0HQBia2I1wDQ5AfEykjRBdWYB8RqSNEE1VgPxRCBmJqSJCSkgO6F0BVFBjubJ1UCcQ5Tz0DRuBWIvUjVJQjOeOdGakDQeB2I9ojVBNepCcy4v0ZqQCpX9QMxDtCaoxnBoqHKSoglU7uUD8TyUTEhkCdsLilpGMsryPoAAAwBD49VaS2wWqwAAAABJRU5ErkJggg==" /></button>',nextArrow:'<button type="button" data-role="none" class="slick-next" aria-label="next"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARhJREFUeNpiYGBgmAnESv///2cgFoOAJxDvAmImojVBdSYD8QYgZiRaE1RjCRBPA2IWQpqYGBCgH4i/AnENAyGAxZNLgLiIKOehadwMxH6kahIH4v1AbE20JqhGMSA+BsT6RGuCatQB4iNAzEe0JqhGT6hT+YnWBNUYAsRrgZiDFE2MQFwIxPNBfEZYAiQGMDIyghLAA5I0QTWeItWmeiD1ixQ/pQHxKlICwhWItwExJ7HxZA2NYHFiU4QqEB8FJSli0x4fEB8GYjNiU7kwEO8FYndSssYaIA4jJrvD4mIekDoLlFyFM75gkQtUzAykGqHBWowvklmQ2GnQHJtOVMECBLHQcoGd2BLWBRpSTKQUy3NJLcsBAgwAKdbSmEpSh+IAAAAASUVORK5CYII=" /><button type="button" data-role="none" class="slick-next" aria-label="next"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARhJREFUeNpiYGBgmAnESv///2cgFoOAJxDvAmImojVBdSYD8QYgZiRaE1RjCRBPA2IWQpqYGBCgH4i/AnENAyGAxZNLgLiIKOehadwMxH6kahIH4v1AbE20JqhGMSA+BsT6RGuCatQB4iNAzEe0JqhGT6hT+YnWBNUYAsRrgZiDFE2MQFwIxPNBfEZYAiQGMDIyghLAA5I0QTWeItWmeiD1ixQ/pQHxKlICwhWItwExJ7HxZA2NYHFiU4QqEB8FJSli0x4fEB8GYjNiU7kwEO8FYndSssYaIA4jJrvD4mIekDoLlFyFM75gkQtUzAykGqHBWowvklmQ2GnQHJtOVMECBLHQcoGd2BLWBRpSTKQUy3NJLcsBAgwAKdbSmEpSh+IAAAAASUVORK5CYII=" /></button>',autoplay:!1,autoplaySpeed:3e3,centerPadding:"50px",cssEase:"ease",dots:!0,dotsClass:"slick-dots",easing:"linear",fade:!0,focusOnSelect:!1,infinite:!0,pauseOnHover:!0,slide:"",slidesToShow:1,slidesToScroll:1,speed:500,variableWidth:!1})
$(".jsSlider-3").slick({autoplay:!0,slidesToShow:1,slidesToScroll:1,arrows:!1,infinite:!0,autoplaySpeed:5e3,pauseOnDotsHover:!0,speed:300,fade:!0,cssEase:"linear"}).on("beforeChange",function(e,t,i,n){var s=$(".benefits__item");s.each(function(){$(this).data("index")===n&&(s.removeClass("active"),$(this).addClass("active"))})})
$(".benefits__item").on("click",function(){$(".jsSlider-3").slick("slickGoTo",$(this).data("index")).slick("slickPause")})
$(".jsSlider-4").slick({arrows:!1,prevArrow:'<button type="button" data-role="none" class="slick-prev" aria-label="previous"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARpJREFUeNpi/P//PwMpgJGRsY2RFE1ADe1AiosBpIkQBqkH4lwgXgrmE6nJG4g3ATEbUZqAwBGIDwKxCFyMgAZNID4CxMIo4ng0CADxUSA2wpDDoUEEiPcCsQtWeRya1gJxCE5XYNEwH4gr8PkVHrnAiGMGUi1AzAIUK8UXySxI7AwgFgXidIJJA2pTDBBvgUUeEXHHYACNbRZiNMA0HQBia2I1wDQ5AfEykjRBdWYB8RqSNEE1VgPxRCBmJqSJCSkgO6F0BVFBjubJ1UCcQ5Tz0DRuBWIvUjVJQjOeOdGakDQeB2I9ojVBNepCcy4v0ZqQCpX9QMxDtCaoxnBoqHKSoglU7uUD8TyUTEhkCdsLilpGMsryPoAAAwBD49VaS2wWqwAAAABJRU5ErkJggg==" /><button type="button" data-role="none" class="slick-prev" aria-label="previous"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARpJREFUeNpi/P//PwMpgJGRsY2RFE1ADe1AiosBpIkQBqkH4lwgXgrmE6nJG4g3ATEbUZqAwBGIDwKxCFyMgAZNID4CxMIo4ng0CADxUSA2wpDDoUEEiPcCsQtWeRya1gJxCE5XYNEwH4gr8PkVHrnAiGMGUi1AzAIUK8UXySxI7AwgFgXidIJJA2pTDBBvgUUeEXHHYACNbRZiNMA0HQBia2I1wDQ5AfEykjRBdWYB8RqSNEE1VgPxRCBmJqSJCSkgO6F0BVFBjubJ1UCcQ5Tz0DRuBWIvUjVJQjOeOdGakDQeB2I9ojVBNepCcy4v0ZqQCpX9QMxDtCaoxnBoqHKSoglU7uUD8TyUTEhkCdsLilpGMsryPoAAAwBD49VaS2wWqwAAAABJRU5ErkJggg==" /></button>',nextArrow:'<button type="button" data-role="none" class="slick-next" aria-label="next"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARhJREFUeNpiYGBgmAnESv///2cgFoOAJxDvAmImojVBdSYD8QYgZiRaE1RjCRBPA2IWQpqYGBCgH4i/AnENAyGAxZNLgLiIKOehadwMxH6kahIH4v1AbE20JqhGMSA+BsT6RGuCatQB4iNAzEe0JqhGT6hT+YnWBNUYAsRrgZiDFE2MQFwIxPNBfEZYAiQGMDIyghLAA5I0QTWeItWmeiD1ixQ/pQHxKlICwhWItwExJ7HxZA2NYHFiU4QqEB8FJSli0x4fEB8GYjNiU7kwEO8FYndSssYaIA4jJrvD4mIekDoLlFyFM75gkQtUzAykGqHBWowvklmQ2GnQHJtOVMECBLHQcoGd2BLWBRpSTKQUy3NJLcsBAgwAKdbSmEpSh+IAAAAASUVORK5CYII=" /><button type="button" data-role="none" class="slick-next" aria-label="next"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARhJREFUeNpiYGBgmAnESv///2cgFoOAJxDvAmImojVBdSYD8QYgZiRaE1RjCRBPA2IWQpqYGBCgH4i/AnENAyGAxZNLgLiIKOehadwMxH6kahIH4v1AbE20JqhGMSA+BsT6RGuCatQB4iNAzEe0JqhGT6hT+YnWBNUYAsRrgZiDFE2MQFwIxPNBfEZYAiQGMDIyghLAA5I0QTWeItWmeiD1ixQ/pQHxKlICwhWItwExJ7HxZA2NYHFiU4QqEB8FJSli0x4fEB8GYjNiU7kwEO8FYndSssYaIA4jJrvD4mIekDoLlFyFM75gkQtUzAykGqHBWowvklmQ2GnQHJtOVMECBLHQcoGd2BLWBRpSTKQUy3NJLcsBAgwAKdbSmEpSh+IAAAAASUVORK5CYII=" /></button>',autoplay:!1,autoplaySpeed:3e3,centerPadding:"50px",cssEase:"ease",dots:!0,dotsClass:"slick-dots",easing:"linear",fade:!0,focusOnSelect:!1,infinite:!0,pauseOnHover:!0,slide:"",slidesToShow:1,slidesToScroll:1,speed:500,variableWidth:!1})
$(".jsSlider-5").slick({prevArrow:'<button type="button" data-role="none" class="slick-prev" aria-label="previous"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARpJREFUeNpi/P//PwMpgJGRsY2RFE1ADe1AiosBpIkQBqkH4lwgXgrmE6nJG4g3ATEbUZqAwBGIDwKxCFyMgAZNID4CxMIo4ng0CADxUSA2wpDDoUEEiPcCsQtWeRya1gJxCE5XYNEwH4gr8PkVHrnAiGMGUi1AzAIUK8UXySxI7AwgFgXidIJJA2pTDBBvgUUeEXHHYACNbRZiNMA0HQBia2I1wDQ5AfEykjRBdWYB8RqSNEE1VgPxRCBmJqSJCSkgO6F0BVFBjubJ1UCcQ5Tz0DRuBWIvUjVJQjOeOdGakDQeB2I9ojVBNepCcy4v0ZqQCpX9QMxDtCaoxnBoqHKSoglU7uUD8TyUTEhkCdsLilpGMsryPoAAAwBD49VaS2wWqwAAAABJRU5ErkJggg==" /><button type="button" data-role="none" class="slick-prev" aria-label="previous"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARpJREFUeNpi/P//PwMpgJGRsY2RFE1ADe1AiosBpIkQBqkH4lwgXgrmE6nJG4g3ATEbUZqAwBGIDwKxCFyMgAZNID4CxMIo4ng0CADxUSA2wpDDoUEEiPcCsQtWeRya1gJxCE5XYNEwH4gr8PkVHrnAiGMGUi1AzAIUK8UXySxI7AwgFgXidIJJA2pTDBBvgUUeEXHHYACNbRZiNMA0HQBia2I1wDQ5AfEykjRBdWYB8RqSNEE1VgPxRCBmJqSJCSkgO6F0BVFBjubJ1UCcQ5Tz0DRuBWIvUjVJQjOeOdGakDQeB2I9ojVBNepCcy4v0ZqQCpX9QMxDtCaoxnBoqHKSoglU7uUD8TyUTEhkCdsLilpGMsryPoAAAwBD49VaS2wWqwAAAABJRU5ErkJggg==" /></button>',nextArrow:'<button type="button" data-role="none" class="slick-next" aria-label="next"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARhJREFUeNpiYGBgmAnESv///2cgFoOAJxDvAmImojVBdSYD8QYgZiRaE1RjCRBPA2IWQpqYGBCgH4i/AnENAyGAxZNLgLiIKOehadwMxH6kahIH4v1AbE20JqhGMSA+BsT6RGuCatQB4iNAzEe0JqhGT6hT+YnWBNUYAsRrgZiDFE2MQFwIxPNBfEZYAiQGMDIyghLAA5I0QTWeItWmeiD1ixQ/pQHxKlICwhWItwExJ7HxZA2NYHFiU4QqEB8FJSli0x4fEB8GYjNiU7kwEO8FYndSssYaIA4jJrvD4mIekDoLlFyFM75gkQtUzAykGqHBWowvklmQ2GnQHJtOVMECBLHQcoGd2BLWBRpSTKQUy3NJLcsBAgwAKdbSmEpSh+IAAAAASUVORK5CYII=" /><button type="button" data-role="none" class="slick-next" aria-label="next"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAdCAYAAABxPebnAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAARhJREFUeNpiYGBgmAnESv///2cgFoOAJxDvAmImojVBdSYD8QYgZiRaE1RjCRBPA2IWQpqYGBCgH4i/AnENAyGAxZNLgLiIKOehadwMxH6kahIH4v1AbE20JqhGMSA+BsT6RGuCatQB4iNAzEe0JqhGT6hT+YnWBNUYAsRrgZiDFE2MQFwIxPNBfEZYAiQGMDIyghLAA5I0QTWeItWmeiD1ixQ/pQHxKlICwhWItwExJ7HxZA2NYHFiU4QqEB8FJSli0x4fEB8GYjNiU7kwEO8FYndSssYaIA4jJrvD4mIekDoLlFyFM75gkQtUzAykGqHBWowvklmQ2GnQHJtOVMECBLHQcoGd2BLWBRpSTKQUy3NJLcsBAgwAKdbSmEpSh+IAAAAASUVORK5CYII=" /></button>',autoplay:!1,autoplaySpeed:3e3,centerPadding:"50px",cssEase:"ease",dots:!0,dotsClass:"slick-dots",easing:"linear",focusOnSelect:!1,infinite:!0,pauseOnHover:!0,slide:"",slidesToShow:1,slidesToScroll:1,speed:500,variableWidth:!1})
$("#jsSlider-6").slick({arrows:!1,autoplay:!1,autoplaySpeed:3e3,centerPadding:"50px",cssEase:"ease",dots:!1,dotsClass:"slick-dots",easing:"linear",focusOnSelect:!1,infinite:!0,pauseOnHover:!0,slide:"",slidesToShow:2,slidesToScroll:1,speed:500,variableWidth:!1})
$("#priceSlide1_prev").click(function(){$("#jsSlider-6").slick("slickPrev")})
$("#priceSlide1_next").click(function(){$("#jsSlider-6").slick("slickNext")})
$("#jsSlider-7").slick({arrows:!1,autoplay:!1,autoplaySpeed:3e3,centerPadding:"50px",cssEase:"ease",dots:!1,dotsClass:"slick-dots",easing:"linear",focusOnSelect:!1,infinite:!0,pauseOnHover:!0,slide:"",slidesToShow:4,slidesToScroll:1,speed:500,variableWidth:!1})
$("#priceSlide2_prev").click(function(){$("#jsSlider-7").slick("slickPrev")})
$("#priceSlide2_next").click(function(){$("#jsSlider-7").slick("slickNext")})
$("#tabContainer1").easytabs({updateHash:!1})
$("#tabContainer2").easytabs({updateHash:!1})
$("#tabContainer3").easytabs({updateHash:!1})
$("#tabContainer4").easytabs({updateHash:!1})
$(".price__nav-item > a").click(function(){var e=$(this).data("tab");$(this).parent().addClass("active").siblings().removeClass("active")
$(".price__tab").each(function(){$(this).attr("id")===e&&$(this).addClass("active").siblings().removeClass("active")})})
$("#js-numbers").waypoint(function(e){"down"===e&&($("#jsNumber1").animateNumber({number:8,easing:"ease"},2e3),$("#jsNumber2").animateNumber({number:25,easing:"ease"},2e3),$("#jsNumber3").animateNumber({number:5,easing:"ease"},2e3),$("#jsNumber4").animateNumber({number:5,easing:"ease"},2e3),$("#jsNumber5").animateNumber({number:17,easing:"ease"},2e3))},{offset:"90%",triggerOnce:!0})
$(".js-products__item").waypoint(function(e){"down"===e&&$(this).removeClass("fadeOut").addClass("fadeIn"),"up"===e&&$(this).removeClass("fadeIn").addClass("fadeOut")},{offset:"70%"})
//$("#jsForm_1").validate({rules:{Name:{required:!0,minlength:2,maxlength:100},Email:{required:!1,minlength:2,maxlength:100},Phone:{required:!0,minlength:2,maxlength:100}},messages:{Name:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Email:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Phone:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""}},submitHandler:function(form){$('#jsForm_1').submit();}})
//$("#jsForm_2").validate({rules:{Name:{required:!0,minlength:2,maxlength:100},Email:{required:!1,minlength:2,maxlength:100},Phone:{required:!0,minlength:2,maxlength:100}},messages:{Name:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Email:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Phone:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""}},submitHandler:function(form){$('#jsForm_1').submit();}})
//$("#jsForm_3").validate({rules:{Name:{required:!0,minlength:2,maxlength:100},Email:{required:!1,minlength:2,maxlength:100},Phone:{required:!0,minlength:2,maxlength:100}},messages:{Name:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Email:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Phone:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""}},submitHandler:function(form){$('#jsForm_1').submit();}})
//$("#jsForm_4").validate({rules:{Name:{required:!0,minlength:2,maxlength:100},Email:{required:!1,minlength:2,maxlength:100},Phone:{required:!0,minlength:2,maxlength:100}},messages:{Name:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Email:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Phone:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""}},submitHandler:function(form){$('#jsForm_1').submit();}})
//$("#jsForm_5").validate({rules:{Name:{required:!0,minlength:2,maxlength:100},Email:{required:!0,minlength:2,maxlength:100},Phone:{required:!0,minlength:2,maxlength:100},Program:{required:!0,minlength:2,maxlength:100},Lang:{required:!0},Date:{required:!0,minlength:2,maxlength:100}},messages:{Name:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Email:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Phone:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Program:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Date:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""}},submitHandler:function(form){$('#jsForm_1').submit();}})
//$("#jsForm_modal").validate({rules:{Name:{required:!0,minlength:2,maxlength:100},Email:{required:!1,minlength:2,maxlength:100},Phone:{required:!0,minlength:2,maxlength:100}},messages:{Name:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Email:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""},Phone:{required:"Поле обязательно для заполнения!",minlength:"Поле не должно содержать менее 2-х символов",maxlength:""}},submitHandler:function(form){formLoad(form);}})})
//function formLoad(form){$('button.btn').addClass('disabled').attr('disabled',true).text('Отправка...').css({'cursor':'default','background':'#ccc'});$(form).submit();}
//$('.main__form-btn').on('click', function() {
//	$('#jsForm_1').submit();
});